# Generated by Django 3.2.6 on 2021-08-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstmodel',
            name='image',
            field=models.FileField(default=None, upload_to='img/upload/'),
        ),
    ]
