# Generated by Django 3.2.6 on 2021-08-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0003_rename_firstmodel_carouselcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestBurger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=80)),
                ('price', models.IntegerField(max_length=10)),
                ('image', models.FileField(default=None, upload_to='img/upload/')),
            ],
        ),
    ]
