# Generated by Django 3.2.6 on 2021-08-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0005_presidentburger'),
    ]

    operations = [
        migrations.CreateModel(
            name='HamburgerClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('image', models.FileField(default=None, upload_to='img/upload/')),
                ('author', models.CharField(max_length=80)),
                ('grade', models.IntegerField(default=1, verbose_name=5)),
            ],
        ),
    ]
