# Generated by Django 3.2.6 on 2021-08-16 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0006_hamburgerclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburgerclient',
            name='grade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
