# Generated by Django 3.2.6 on 2021-08-16 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0007_alter_hamburgerclient_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestburger',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hamburgerclient',
            name='comment',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='hamburgerclient',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='presidentburger',
            name='price',
            field=models.IntegerField(),
        ),
    ]
