# Generated by Django 3.2.6 on 2021-08-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0010_ourgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=80)),
                ('comments', models.IntegerField(default=0)),
                ('image', models.FileField(default=None, upload_to='img/burgers/')),
                ('day', models.DateField()),
                ('month', models.DateField()),
            ],
        ),
    ]
