# Generated by Django 3.2.6 on 2021-08-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0012_remove_blogpost_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=80)),
                ('comments', models.IntegerField(default=0)),
                ('image', models.FileField(default=None, upload_to='img/burgers/')),
            ],
        ),
    ]
