# Generated by Django 3.2.6 on 2021-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0014_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='getInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=150)),
            ],
        ),
    ]
