# Generated by Django 3.2.6 on 2021-08-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0015_getintouch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestburger',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
